!
! vsm: this file is an example of file generated by compilation script
! and includes model domain parameters: size, resolution, location
!
! im=im_local and jm=jm_local in pom.h
        integer,parameter:: im=722,jm=386,km=50
!       integer,parameter:: im=83,jm=56,km=21
!       integer,parameter:: im=83,jm=29,km=21
!       integer,parameter:: im=29,jm=29,km=21
